# Generated by Django 5.0 on 2023-12-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_car_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='name',
            new_name='car_name',
        ),
    ]
